### ISSUE TITLE
How do I get this to work - the inbuilt ADAX integration seems to take priority

### ISSUE THREAD

**Issue by ianfretwell** [Danielhiversen/home_assistant_adax_local#3]
I've been using the 'default' ADAX integration (which I believe is your own work too) but wanted to use local access.
I raised this as an issue/feature request on the other repo note knowing that this one even existed and was pointed here.

I can't get it to work though because after adding as as custom-repo in HACS and installing it appears to be impossible to add it to HA because when you search for ADAX the only entry shown is for the (in-built) cloud version. If I add that anyway I get the prompt for account id and password rather than wifi ssid and password.

What am I doing wrong (or are both versions trying to call themselves exactly the same thing) ?

Thanks.

**Comment by lhrmota** [comment]
Hi.
I own heaters both with and without bluetooth, and thus this issue interests me...
Can the local and cloud integrations coexist in the same HA installation? 
Or must I use the cloud integration in order to control both types of heaters?
Thanks and best regards

**Comment by ianfretwell** [comment]
Apparently the integration is going to be able to do both cloud and local with the release of HA 2022.2 in early Feb - so you should be good in a week or so!

**Comment by lhrmota** [comment]
Oh, that's great, thanks for the info!
